### PR TITLE
Feature/workspacify

### PR DESCRIPTION
**Pull request by hoodie**
Heyho,
I took the liberty to turn this into a 'monorepo', as these are so hip nowadays. All it does it pull node-api-sys into this repo and make turn it all into a cargo-workspace. You should be able to build with `cargo build --all`.

### CODE REVIEW

**Comment by jupp0r** [comment]
Thanks, looks mostly good. Can you rebase to master?

**Comment by hoodie** [comment]
I would suggest a good old merge here, as I joined the two repos via subtree.

**Comment by jupp0r** [comment]
Can you just copy instead of using subtree? I'd rather have them in one repo and delete node-sys

**Comment by hoodie** [comment]
sure can do, I just meant to keep the original history around

**Comment by jupp0r** [comment]
Thanks for the effort, it's just not worth it. It's 100% autogenerated by bindgen.

**Comment by hoodie** [comment]
done

**Comment by jupp0r** [comment]
Thanks man!

**Pull request merged**
